config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'pages#index'
  get 'societe'                          =>'pages#societe'
  get 'ressources'                       =>'pages#ressources'
  get 'missions'                         =>'pages#missions'
  get 'contact'                          =>'pages#contact'
  get 'articles'                         =>'articles#index'
  get 'articles/:title'                  =>'articles#view',as:'show_details'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/article.rb
class Article < ActiveRecord::Base
  has_attached_file :image
  has_attached_file :image1
  has_attached_file :image2
  has_attached_file :image3
  has_attached_file :image4
  has_attached_file :image5
  has_attached_file :plant
  has_attached_file :plant1
  has_attached_file :plant2
  has_attached_file :plant3
  has_attached_file :plant4
  has_attached_file :plant5
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image1, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image2, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image3, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image4, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :image5, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :plant, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :plant1, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :plant2, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :plant3, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :plant4, content_type: /\Aimage\/.*\Z/
  validates_attachment_content_type :plant5, content_type: /\Aimage\/.*\Z/
end

app/models/categorie.rb
class Categorie < ActiveRecord::Base
end

app/models/mission.rb
class Mission < ActiveRecord::Base
end

app/models/ressource.rb
class Ressource < ActiveRecord::Base
end

app/models/societe.rb
class Societe < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all.order(id: :desc)
  end

  def view
    @article = Article.find_by_title(params[:title])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @societes = Societe.all
  end

  def societe
    @societes = Societe.all
  end

  def ressources
    @ressources = Ressource.all
  end

  def missions
    @missions = Mission.all
  end

  def contact

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/index.html.erb
<% @title = 'nos realisations' %>
<% @meta_description = "EFT2E Ingénierie est un bureau d'études spécialisé dans la réalisation des études de conception et d'exécution de fluides techniques et thermiques du bâtiment" %>
<% @meta_keyword = ' Etudes, Fluides, Thermiques, Energies, Environnement, bureau d études, énergies renouvelables, écoute, conseils, objectifs énergétiques, environnementaux, économiques'%>
<div class="container content azaz">
  <div class="row">
    <div class="col-sm-12 caroupad">
      <div id="carousel" class="carousel slide">
        <div class="carousel-inner">
          <div class="item active">
            <%= link_to '' do %>
                <%= image_tag 'SALLE_DES_FETES SURBOURG.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>Salle des fêtes à Surbourg</h2>
              <h2>©Forum de l’Architecture Marc Klipfel</h2>
            </div>
          </div>
          <div class="item">
            <%= link_to 'articles/Ecole-primaire-de-Batzendorf-(67)' do %>
                <%= image_tag 'ECOLE BATZENDORF 2.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>Ecole primaire de Batzendorf</h2>
              <h2>©Architectes Larché & Metzger</h2>
            </div>
          </div>

          <div class="item">
            <%= link_to 'articles/44-logements-à-Brumath-(67)-Concours-non-lauréat-(2ème)' do %>
                <%= image_tag '44 LOGEMENTS COLLECTIFS BRUMATH.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>44 logements collectifs à Brumath</h2>
              <h2>©Marc Thomas Architecte</h2>
            </div>
          </div>
          <div class="item">
            <%= link_to 'articles/Ecole-primaire-de-Batzendorf-(67)' do %>
                <%= image_tag 'ECOLE BATZENDORF 3.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>Ecole primaire de Batzendorf</h2>
              <h2>©Architectes Larché & Metzger</h2>
            </div>
          </div>
          <div class="item">
            <%= link_to '/articles/Maison-de-la-petite-enfance-de-la-Robertsau-à-Strasbourg-(67)' do %>
                <%= image_tag 'MAISON PETITE ENFANCE ROBERTSAU STRASBOURG.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>Maison de la petite enfance Robertsau Strasbourg</h2>
              <h2>©Atelier Architecture & Soleil</h2>
            </div>
          </div>
          <div class="item">
            <%= link_to 'articles/25-logements-à-Ostwald-(67)-Concours-non-lauréat-(2ème)' do %>
                <%= image_tag '25 LOGEMENTS OSTWALD.jpg'%>
            <% end %>
            <div class="carousel-caption">
              <h2>25 logements collectifs à Ostwald</h2>
              <h2>©Marc Thomas Architecte</h2>
            </div>
          </div>
          <div class="item">
            <%= link_to 'articles/Ecole-primaire-de-Batzendorf-(67)' do %>
                <%= image_tag 'ECOLE BATZENDORF.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>Ecole primaire de Batzendorf</h2>
              <h2>©Architectes Larché & Metzger</h2>
            </div>
          </div>
          <div class="item">
            <%= link_to 'articles/Ecole-maternelle-et-élémentaire-de-Goxwiller-(67)' do %>
                <%= image_tag 'ECOLE GOXWILLER.png'%>
            <% end %>
            <div class="carousel-caption">
              <h2>Ecole maternelle de Goxwiller</h2>
              <h2>©Architectes Larché & Metzger</h2>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
  <div class="societe menu-filters" data-stickycat>
    <ul id="filters" class="filters">
      <li>
        <span class="filter active" data-filter="cat1 cat2 cat3 cat4 cat5 cat6 cat7 cat8 cat9 cat10 cat11 cat12">Tout</span>
      </li>
      <li>
        <span class="filter" data-filter="cat1 cat2">Habitat</span>
      </li>
      <li>
        <span class="filter" data-filter="cat3">Tertiaire</span>
      </li>
      <li>
        <span class="filter" data-filter="cat4">Social</span>
      </li>
      <li>
        <span class="filter" data-filter="cat5">Culturel</span>
      </li>
      <li>
        <span class="filter" data-filter="cat6">Enseignement</span>
      </li>
      <li>
        <span class="filter" data-filter="cat7">Sportif</span>
      </li>
      <li>
        <span class="filter" data-filter="cat8">Industriel</span>
      </li>
      <li>
        <span class="filter" data-filter="cat9">Médical</span>
      </li>
      <li>
        <span class="filter" data-filter="cat10">Concours</span>
      </li>
      <li>
        <span class="filter" data-filter="cat11">Hébergement</span>
      </li>
      <li>
        <span class="filter" data-filter="cat12">Commerce</span>
      </li>
    </ul>
  </div>
<div class="container-vue container content container-fluid-index">
    <div id="articleliste" class="clear articlelist ">
      <% @articles.each do|article|%>
          <a href="/articles/<%= article.title %>">
            <div class="carte cat<%= article.category %>" data-cat="cat<%=article.category%>">
              <div class="carte-image">
                <%= image_tag(article.image.url(:original)) %>
              </div>
              <div class="carte-body">
                <div class="carte-title">
                  <h2><%= article.titre %></h2>
                </div>
                <div>
                  <div class="carte-description">
                    <p><%= article.description %></p>
                  </div>
                </div>
              </div>
            </div>
          </a>
      <%end%>
    </div>
</div>

app/views/articles/view.html.erb
<% @title = @article.titre %>
<% @meta_description = @article.description %>
<% @meta_keyword = 'CE, CCTP, DPGF, DQE, plans DAO, chauffage, ventilation, climatisation, rafraîchissement,
solaire, thermique, désenfumage, régulation, GTC, BBC+, STD, Simulation Thermo-Dynamique, Infiltrométrie, infra-rouge, Certification RT2012, Chauffage, ventilation, sanitaire , assainissement, électricité' %>
  <div class="article-title content">
    <h1><strong><%= @article.titre%></strong></h1>
  </div>
  <!--boite modal-->
 <div class="modal" id="infos">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">x</button>
  <h3>fiche technique</h3>
        </div>
        <div class="modal-body">

          <div class="article-object">
            <hr>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet1col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet1col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet2col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet2col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet3col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet3col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet4col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet4col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet5col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet5col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet6col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet6col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet7col1 %></p>
              </div>
              <div class="article-object-col2">
                <p><strong><%= @article.objet7col2 %></strong></p>
              </div>
            </div>
            <div class="article-object-col">
              <div class="article-object-col1">
                <p><%= @article.objet8col1 %></p>
              </div>
              <div class="article-object-col2">
               <p><strong><%= @article.objet8col2 %></strong></p>
              </div>
            </div>
          </div><!--/article-objet-->
        </div><!--/modalbody-->
        <div class="modal-footer">
          <button class="btn btn-info" data-dismiss="modal">Fermer</button>
        </div>
      </div>
    </div><!--/modal-dialogue-->
  </div><!--/modal-->
  <!-- carousel1-->
  <div>
    <div id="carou1" class="content content-vue container soci">
      <div class="row">
        <div>
          <div id="carousel" class="carousel slide carouvue">
            <div class="carousel-inner">
              <%if @article.image.present?%>
                  <div class="item active">
                    <%= image_tag(@article.image.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.image1.present?%>
                  <div class="item">
                    <%= image_tag(@article.image1.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.image2.present?%>
                  <div class="item">
                    <%= image_tag(@article.image2.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.image3.present?%>
                  <div class="item">
                    <%= image_tag(@article.image3.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.image4.present?%>
                  <div class="item">
                    <%= image_tag(@article.image4.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.image5.present?%>
                  <div class="item">
                    <%= image_tag(@article.image5.url(:original)) %>
                  </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>


    <!-- carousel2-->
    <div id="carou2" class="content content-vue container desactiver soci">
      <div class="row">
        <div>
          <div id="carousel" class="carousel slide carouvue">
            <div class="carousel-inner">
              <%if @article.plant.present?%>
                  <div class="item active">
                    <%= image_tag(@article.plant.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.plant1.present?%>
                  <div class="item">
                    <%= image_tag(@article.plant1.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.plant2.present?%>
                  <div class="item">
                    <%= image_tag(@article.plant2.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.plant3.present?%>
                  <div class="item">
                    <%= image_tag(@article.plant3.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.plant4.present?%>
                  <div class="item">
                    <%= image_tag(@article.plant4.url(:original)) %>
                  </div>
              <%end%>
              <%if @article.plant5.present?%>
                  <div class="item">
                    <%= image_tag(@article.plant5.url(:original)) %>
                  </div>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="footer">
      <div class="row">
        <div class="center-btn">
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-success" id="previous">
              <input type="radio" name="options"><span class="glyphicon glyphicon-step-backward"></span>
            </label>
            <label class="btn btn-success" id="pause">
              <input type="radio" name="options"><span class="glyphicon glyphicon-pause"></span>
            </label>
            <label class="btn btn-success active" id="play">
              <input type="radio" name="options"><span class="glyphicon glyphicon-play"></span>
            </label>
            <label class="btn btn-success" id="next">
              <input type="radio" name="options"><span class="glyphicon glyphicon-step-forward"></span>
            </label>
          </div>
        </div>
      </div>
      <div class="navigation-navbar">
        <ul>
          <li><a href="#" id="photos">photos</a></li>
          <li><a href="#" id="plants">plans</a></li>
          <li><a data-toggle="modal" href="#infos">fiche technique</a></li>
        </ul>
      </div>
    </div>
  </div>

app/views/layouts/_footer.html.erb
<footer class="societe content">
  <div class="fb-link">
    <p class="fb">
        <%= link_to 'https://www.facebook.com/eft2e.ingenierie', target: '_blank' do %>
            <%= image_tag 'facebook-icon-logo-vector-400x400.png', class: 'facebook'%>
        <% end %>
        <%= link_to 'https://twitter.com/EFT2E_Ing', target: '_blank' do %>
            <%= image_tag 'twitter.png', class: 'twitter'%>
        <%end%>
        <%= link_to('Contact', contact_path, class: 'und') %>
    </p>
    <p class="fb fb-link">
      <a data-toggle="modal" href="#info">Copyright</a>
      © 2016 EFT2E INGÉNIERIE</p>
    <div class="modal" id="info">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal">x</button>
            <h3 class="modal-title">copyright</h3>
          </div>

          <div class="modal-body">
            <div content="modal-title">
              <h4>Société</h4>
            </div>
            <p>EFT2E Ingénierie</p>
            <P>3 C rue de Hochfelden 67170 Brumath</P>
            <P>Tél/Fax: 09 80 67 46 76</P>
            <P>EURL au capital de 5000 €</P>
            <p>SIRET: 80086565100015</p>
            <p>APE: 7112B</p>
            <p>Representé par M.EDEL Julien</p>
            <div content="modal-title">
              <h4>Hébergement</h4>
            </div>
              <p>OVH</p>
              <p>SAS au capital de 10 000 000 €</p>
              <p>RCS Roubaix- tourcoing 424 761 419 00045</p>
              <p>Code APE: 6202A</p>
              <p>N TVA: RF 22 424 761 419</p>
              <p>Siège social : 2 rue Kellermann - 59100 Roubaix - France.</p>
            <h4>Copyright</h4>
              <p>Tous droits réservés à EFT2E Ingénierie</p>
            <p>Toutes les images et plans sont utilisés avec l'autorisation des auteurs</p>
          </div><!--/modalbody-->
          <div class="modal-footer">
            <button class="btn btn-info" data-dismiss="modal">Fermer</button>
          </div>
        </div>
      </div><!--/modal-dialogue-->
    </div><!--/modal-->
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="societe content">
    <div class="header-title">
      <%= image_tag 'logo-eft2e.png'%>
      <div class="header-title-titre">
        <h1 class="big"><div class="texte">BUREAU D'ETUDES</div> <div class="texte">EFT2E <div
        class="tate">INGENIERIE</div></div></h1>
        <h2 class="big under"><div class="gris"><b>E</b>tudes <b>F</b>luides <b>T</b>hermiques </div><div class="vert"><b>E</b>nergies & <b>E</b>nvironnement</div></h2>
      </div>
    </div>
  </div>

  <div class="header-navbar societe content" data-sticky>
    <nav>
      <ul  class="menu-hide">
        <li><%= link_to('Accueil', root_url)%></li>
        <li><%= link_to('Société', societe_url)%></li>
        <li><%= link_to('Ressources', ressources_url)%></li>
        <li><%= link_to('Missions',missions_url)%></li>
        <li><%= link_to('Réalisations', articles_url)%></li>
        <li><%= link_to('contact', contact_url)%></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="fr">
  <head>
    <title><%=@title%></title>
      <%= stylesheet_link_tag 'application', media: 'all' %>
      <%= csrf_meta_tags %>
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
      <meta name="viewport" content="minimum-scale=0.25, maximum-scale=1.2"/>
      <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
      <meta name="language" content="fr" />
      <meta name="description" content="<%= @meta_description %>">
      <meta name="keywords" content="<%= @meta_keyword %>" />
      <meta name="copyright" content="//eft2e-ing.fr" />

  </head>
  <body>
    <%= render(partial: 'layouts/header')%>
    <div class="con-flu">
      <%= yield %>
    </div>
    <%= render(partial: 'layouts/footer')%>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/contact.html.erb
<% @title = 'contact' %>
<% @meta_description = "EFT2E Ingénierie est un bureau d'études spécialisé dans la réalisation des études de conception et d'exécution de fluides techniques et thermiques du bâtiment" %>
<% @meta_keyword = ' Etudes, Fluides, Thermiques, Energies, Environnement, bureau d études, énergies renouvelables, écoute, conseils, objectifs énergétiques, environnementaux, économiques, contacter'%>
  <div class="contacts content container">
    <div>
      <div class="row">
        <div class="col-sm-12 caroupad">
          <div id="carousel" class="carousel slide">
            <div class="carousel-inner">
              <div class="item active">
                <%= link_to 'articles/25-logements-à-Ostwald-(67)-Concours-non-lauréat-(2ème)' do %>
                    <%= image_tag '25 LOGEMENTS OSTWALD.jpg'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>25 logements collectifs à Ostwald</h2>
                  <h2>©Marc Thomas Architecte</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to 'articles/Ecole-maternelle-et-élémentaire-de-Goxwiller-(67)' do %>
                    <%= image_tag 'ECOLE GOXWILLER.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>Ecole maternelle de Goxwiller</h2>
                  <h2>©Architectes Larché & Metzger</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to '/articles/Maison-de-la-petite-enfance-de-la-Robertsau-à-Strasbourg-(67)' do %>
                    <%= image_tag 'MAISON PETITE ENFANCE ROBERTSAU STRASBOURG.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>Maison de la petite enfance Robertsau Strasbourg</h2>
                  <h2>©Atelier Architecture & Soleil</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to 'articles/44-logements-à-Brumath-(67)-Concours-non-lauréat-(2ème)' do %>
                    <%= image_tag '44 LOGEMENTS COLLECTIFS BRUMATH.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>44 logements collectifs à Brumath</h2>
                  <h2>©Marc Thomas Architecte</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to 'articles/Ecole-primaire-de-Batzendorf-(67)' do %>
                    <%= image_tag 'ECOLE BATZENDORF.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>Ecole primaire de Batzendorf</h2>
                  <h2>©Architectes Larché & Metzger</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to 'articles/Ecole-primaire-de-Batzendorf-(67)' do %>
                    <%= image_tag 'ECOLE BATZENDORF 2.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>Ecole primaire de Batzendorf</h2>
                  <h2>©Architectes Larché & Metzger</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to 'articles/Ecole-primaire-de-Batzendorf-(67)' do %>
                    <%= image_tag 'ECOLE BATZENDORF 3.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>Ecole primaire de Batzendorf</h2>
                  <h2>©Architectes Larché & Metzger</h2>
                </div>
              </div>
              <div class="item">
                <%= link_to '' do %>
                    <%= image_tag 'SALLE_DES_FETES SURBOURG.png'%>
                <% end %>
                <div class="carousel-caption">
                  <h2>Salle des fêtes à Surbourg</h2>
                  <h2>©Forum de l’Architecture Marc Klipfel</h2>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="btn-cent">
          <div class="btn-group" data-toggle="buttons">
            <label class="btn btn-success" id="previous">
              <input type="radio" name="options"><span class="glyphicon glyphicon-step-backward"></span>
            </label>
            <label class="btn btn-success" id="pause">
              <input type="radio" name="options"><span class="glyphicon glyphicon-pause"></span>
            </label>
            <label class="btn btn-success active" id="play">
              <input type="radio" name="options"><span class="glyphicon glyphicon-play"></span>
            </label>
            <label class="btn btn-success" id="next">
              <input type="radio" name="options"><span class="glyphicon glyphicon-step-forward"></span>
            </label>
          </div>
        </div>
      </div>
    </div>
    <h2 class="droite">NOUS CONTACTER</h2>
    <hr>
    <h2>EFT2E INGÉNIERIE </h2>
    <p><strong><b>Adresse :</b> 3C rue de Hochfelden 67170 Brumath</strong></p>
    <p><strong><b>Tél/Fax :</b> 09 80 67 46 76</strong></p>
    <p><strong><b>Email :</b> contact@eft2e-ingenierie.fr</strong></p>
    <p><strong><b>Bureaux ouverts : </b> du lundi au vendredi de 9h à 18h</strong></p>

  </div>